baseURL = "https://frei.picures"
languageCode = "de-DE"
theme = "adritian-free-hugo-theme"

# Plugins
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "css/main.css"
  [[params.plugins.css]]
  URL = "css/rad-icons.css"
  [[params.plugins.css]]
  URL = "css/custom.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "js/rad-animations.js"
  [[params.plugins.js]]
  URL = "js/sticky-header.js"
  [[params.plugins.js]]
  URL = "js/library/fontfaceobserver.js"


# navigation
[menu]

  [[menu.header]]
  name = "Über mich"
  URL = "#about"
  weight = 2

  [[menu.header]]
  name = "Portfolio"
  URL = "#portfolio"
  weight = 3

#  [[menu.header]]
#  name = "Erfahrung"
#  URL = "#experience"
#  weight = 4

  [[menu.header]]
  name = "Blog"
  URL = "/blog"
  weight = 5

 # [[menu.header]]
 # name = "Kontakt"
 # URL = "#contact"
 # weight = 6

  [[menu.footer]]
  name = "Über mich"
  URL = "#about"
  weight = 2

  [[menu.footer]]
  name = "Portfolio"
  URL = "#portfolio"
  weight = 3

  [[menu.footer]]
  name = "Kontakt"
  URL = "mailto:hi@frei.pictures"
  weight = 4

    [[menu.footer]]
  name = "Impressum"
  URL = "impressum.html"
  weight = 5


[params]

  sections = ["showcase", "about", "text", "education", "client-and-work", "contact"]

  homepageExperienceCount = 6

  [params.google_analytics]
      code = "UA-XXXXX-Y"
      enabled = false
  [params.google_tag_manager]
      code = "GTM-XXXXX"
      enabled = false
  
  [params.logo]
    text1 = "Frei"
    text2 = "Pictures"

  [params.footer]
      copyright = "© Sebastian Frei."
      [params.footer.radity_logo]
        x = "img/general/design-and-code-radity.png"
        _2x = "img/general/design-and-code-radity@2x.png"
        alt = "Design & Code - Radity"
